### ISSUE TITLE
Link in the README to the Jupyternotebooks are 404

### ISSUE THREAD

**Issue by Zethson** [ratschlab/HIRID-ICU-Benchmark#11]
All links in the `HiRID data` section return 404.

Would be happy to view the notebooks :)

Thanks!

**Comment by hugoych** [comment]
Hi, 
Thanks for noticing it!
URL had changed, it should be fixed now :)

**Comment by Zethson** [comment]
@hugoych thanks for fixing it with light speed. Looking forward to reading the manuscript next week.
