### ISSUE TITLE
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.

### ISSUE THREAD

**Issue by rvandewater** [ratschlab/HIRID-ICU-Benchmark#16]
I was trying to get the HIRID benchmark working, but when attempting the icu-benchmarks preprocess command, I get the following warning:
_Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process._
This warning repeats every few minutes. The data processing does seem to work, but very slowly (on i9-12900h).
I used the following command to run the preprocessing:

icu-benchmarks preprocess --hirid-data-root "/mnt/c/Users/Robin van de Water/Documents/Datasets/hirid/hirid_icu_benchmark" --work-dir "/mnt/c/Users/Robin van de Water/Documents/Datasets/hirid_benchmark_preprocessed" --var-ref-path ./preprocessing/resources/varref.tsv --split-path ./preprocessing/resources/split.tsv --nr-workers 8

Your work seems great, and I would like to get it running. Thank you in advance for your help.

**Comment by rvandewater** [comment]
Additional question: in the HIRID dataset downloaded from Physionet, there is a merged_stage folder. Does this have the same preprocessing as the data generated by the command above?

**Comment by epierson9** [comment]
Seconded - I am also getting this warning.

**Comment by hugoych** [comment]
Hi @epierson9,
Sorry, we've been discussing the matter with @rvandewater by email and haven't updated this issue yet. 
From our exchange, I believe the error message comes from an OOM issue in the first two steps of pre-processing. To solve the issue you need to raise the required memory per worker to 16 GB (contrary to what is currently indicated in the README, which I'll update). 
@rvandewater can you confirm you no longer have the issue with the increased memory?

I'm currently working on reducing this memory footprint!

**Comment by epierson9** [comment]
ok great! We will rerun as well with larger memory and let you know if that resolves the issue.

**Comment by epierson9** [comment]
In case it's helpful to you as you debug, when we ran with the original memory resources on a system which used slurm, the job didn't finish after 2 days and when I killed it the message was

`slurmstepd: error: Detected 78 oom-kill event(s) in StepId=640378.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.`

**Comment by rvandewater** [comment]
I can confirm @hugoych remarks. 16 GB per worker solved my issue. I also used double the cores as there are workers, just to be sure. So I used 100 GB RAM, 6 cores, and 3 workers to do the preprocessing. It ran within 12 hours on our HPC as far as I can remember.

**Comment by epierson9** [comment]
I ran with 8 workers and 800 GB RAM (perhaps overkill...) and that seems to have solved the issue. Job terminated in 05:09:53 and had no Numba (or other) errors. Last status message is `2022-07-11 03:43:29,582 - INFO: Running build_ml` and the output files look like

<img width="308" alt="Screen Shot 2022-07-11 at 9 27 54 AM" src="https://user-images.githubusercontent.com/2271768/178275053-9ae7832c-6981-432c-a113-7f343a2858ca.png">

which is hopefully what is intended. Thank you for your help!!
