### ISSUE TITLE
Correct value of --hirid-data-root? 

### ISSUE THREAD

**Issue by epierson9** [ratschlab/HIRID-ICU-Benchmark#17]
Hi,

Thank you for providing this public resource! We are attempting to run the data preprocessing and are running into parquet errors. Specifically, after we follow steps 2 + 3 in the downloading data instructions in the readme, and run

python icu_benchmarks/run.py preprocess --hirid-data-root BASE_DIRECTORY_WE_DOWNLOADED_TAR_GZ_FILES_INTO \
                          --work-dir MY_OUTPUT_DIR \
                          --var-ref-path ./preprocessing/resources/varref.tsv \
                          --split-path ./preprocessing/resources/split.tsv \
                          --nr-workers 8

we run into the following error

OSError: Could not open parquet input source 'BASE_DIRECTORY_WE_DOWNLOADED_TAR_GZ_FILES_TO/observation_tables/observation_tables_index.csv': Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.

I assume this is because we are somehow passing in the wrong value of hirid-data-root, since these are indeed CSVs, not parquet files. But we are not sure what path to use instead. Using `BASE_DIRECTORY_WE_DOWNLOADED_TAR_GZ_FILES_INTO/observation_tables/` or `BASE_DIRECTORY_WE_DOWNLOADED_TAR_GZ_FILES_INTO/observation_tables/parquet/` also yields errors.

**Comment by epierson9** [comment]
This error appears to be caused by the fact that the version of `observation_tables` we downloaded has a subdirectory, `parquet`, which the code does not seem to expect. We got this to run by adding `parquet` to the path in several lines in `run.py` - if you can confirm this is correct, we can open a PR or something.

**Comment by hugoych** [comment]
Hi @epierson9, 
Thanks for using our work and catching this! 
Indeed the file organization used to not have a `hirid_root/observation_tables/observation_tables_index.csv` file but directly all the parquet files corresponding as `hirid_root/observation_tables/part-XX.parquet`. 

I need to check with HiRID authors about the change just to be sure. If it's confirmed a PR would be great thanks!

**Comment by epierson9** [comment]
perfect, let me know! thanks for the quick reply :)

**Comment by epierson9** [comment]
Hi,

Just wanted to check in on this - was my fix correct? Would you like me to issue a PR? 

Best,
Emma

**Comment by hugoych** [comment]
Hi Emma, 
Sorry for the late reply! 
I can confirm the file organization has changed; thus, if you have time a PR would be great!

**Comment by epierson9** [comment]
Great, thanks! Hm, for some reason I'm not allowed to add a branch to the repo, which I think I need to do to issue a PR - sorry if I'm doing something wrong, or maybe it's a permissions issue on your end...? 

```
(default_virtualenv) emmapierson@Emmas-MacBook-Pro-3 icu_benchmarks % git push origin pierson_fixing_paths
ERROR: Permission to ratschlab/HIRID-ICU-Benchmark.git denied to epierson9.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by hugoych** [comment]
Hi Emma, 
You indeed can't directly add a branch to the public repo.
To open a PR you need to first "fork" the repo, thus have your version, and then submit a PR from your forked repo to this repo. 
See: 
- https://docs.github.com/en/get-started/quickstart/fork-a-repo#propose-changes-to-someone-elses-project
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

I'll also add a CONTRIBUTING.md file as this was not clear, thanks for raising it!
