### ISSUE TITLE
confirming arterial readings

### ISSUE THREAD

**Issue by michela-meister** [ratschlab/HIRID-ICU-Benchmark#21]
Hello, and thanks for all your help with the data set! We just wanted to confirm the arterial readings we are working with. We found a high fraction of patients (~86%) have a_SO2 and a_Lac readings. Is this what you would expect?
Best,
Michela

**Comment by hugoych** [comment]
Hi Michela, 
 When checking in `merged_stage` patients with at least one entry of a_SO2 (`vm141`) and a_Lac (`vm136`) (not necessarily at the same time), I find 87.8 % of patients concerned. Hope this answers your question!

**Comment by michela-meister** [comment]
Hi Hugo, Thanks! Do you have an idea of whether testing 87% of patients for a_SO2 or a_Lac is typical in this hospital setting?

**Comment by hugoych** [comment]
Hi, 
One thing to note is that these patients are all critically ill patients as they are admitted to the ICU. I'm not a practitioner, so it's hard for me to answer this question. I believe that a_Lac and SaO2 are good proxies to determine whether a subject is suffering from respectively, hypoxemia and septic shock. Thus, checking the most patient for these measures at least once in their stay seems understandable from my point of view. 

For comparison, you might want to check other available databases such as MIMIC-III/IV and eICU, although they come from different regions of the world. 

Hope this answers your question!
